#sdk: "<path to your sdk here>"
sdk: "../../rhomobile/rhodes"
sdkversion: 5.8.0
name: kitchensinkJS
version: 1.0
vendor: rhomobile
build: debug
applog: rholog.txt
javascript_application: true
#ajax_api_bridge: true
iphone:
  configuration: Release
  sdk: iphonesimulator10.2
  BundleIdentifier: com.rhomobile.kitchensinkjs
  BundleURLScheme: kitchensinkjs
  production:
    ipa_itunesartwork_image: "./production/iTunesArtwork.png"
  # Note: Specifies the URL schemes the app is able to call using Rho.System.runApplication
  #ApplicationQueriesSchemes: ["scheme1", "scheme2"]
wp8:
  productid: '98cef7b0-88bb-0134-7b78-60f81db5e3c0'
uwp:
  productid: 'caa0300f-1021-40aa-bb98-27c5547616fa'
android:
  #manifest_template: 'AndroidManifest.erb'
  version: 7.1.1
  # Note: in order to simplify debugging only app messages and system channels with priority informative and higher, and any errors are enabled by default
  logcatFilter: APP:I StrictMode:I DEBUG:I *:E

wm:
  #sdk: "MC3000c50b (ARMV4I)"
  #sdk: "Windows Mobile 6.5.3 Professional DTK (ARMV4I)"
  extensions:
    - webkit

win32:
  msvc: 2015
  deployqt: 1
  deploymsvc: 1

extensions:
  - audiocapture
  - barcode
  - indicators
  - mediacapture
  - hardwarekeys
  - mediaplayer
  - printing
  #- printing_zebra
  - sensor
  - indicators
  - signature

capabilities:
  - gps

rhobundle:
  exclude_items:
  - thumb.db
